#!/bin/sh

export EDITOR="vim"
export TERMINAL="termite"
export BROWSER="google-chrome-stable"

if [[ "$(tty)" = "/dev/tty1" ]]; then
	pgrep i3 || startx
fi

xrandr --output eDP1 --primary --mode 1600x900

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
