export DOTFILES="$HOME/.dotfiles"
export ZSH=$HOME/.oh-my-zsh
export EDITOR="nvim"

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

. $DOTFILES/zsh/aliases.zsh
. $DOTFILES/zsh/functions.zsh
. $DOTFILES/zsh/custom.zsh
. $HOME/scripts/*.sh
. $HOME/.keys

# Plugins - must be above oh-my-zsh sourcing
plugins=(git node zsh-completions zsh-autosuggestions)


# Enable zsh-completion
autoload -Uz compinit && compinit -I

# Fix oh-my-zsh error
ZSH_DISABLE_COMPFIX=true

# Disable autocd
unsetopt autocd

# THEME
ZSH_THEME="robbyrussell"
. $ZSH/oh-my-zsh.sh


# NVM
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Enable vi mode
bindkey -v
bindkey -M viins 'jk' vi-cmd-mode
bindkey '^[[Z' reverse-menu-complete
# source fzf after enable vi mode
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# FZF
# ignore node_modules and .git folders
export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --no-ignore-vcs -g "!{node_modules,.git}"'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_OPTS='--height 75% --reverse'

# Python3 non-sense
#
# export PYENV_ROOT="$HOME/.pyenv"
# export PATH="$PYENV_ROOT/bin:$PATH"
# eval "$(pyenv init --path)"
# eval "$(pyenv init -)"


### Fix slowness of pastes with zsh-syntax-highlighting.zsh
pasteinit() {
  OLD_SELF_INSERT=${${(s.:.)widgets[self-insert]}[2,3]}
  zle -N self-insert url-quote-magic # I wonder if you'd need `.url-quote-magic`?
}

pastefinish() {
  zle -N self-insert $OLD_SELF_INSERT
}
zstyle :bracketed-paste-magic paste-init pasteinit
zstyle :bracketed-paste-magic paste-finish pastefinish

### Fix slowness of pastes
export PATH="/usr/local/opt/maven@3.5/bin:$PATH"
